### ISSUE TITLE
Elegant solution for assigning respID

### ISSUE THREAD

**Issue by willking98** [surveydown-dev/demo-choice-based-conjoint#1]
Hi, I was wondering if the development team has considered how to manage and assign unique `respIDs` to prevent duplicates and handle non-completers. Currently, the code samples with replacement, which can result in duplicate IDs. It would also be useful if IDs from incomplete responses could be reassigned to future participants.

I’ve been working on code to address this, but I’m curious if something similar is already in development.

Cheers, 
Will

**Comment by jhelvy** [comment]
This is something I've thought about before, but on the list of priorities to address I've ignored it for now as random sampling works pretty well. My strategy is basically make my design file quite large so the chance of getting a duplicate are relatively low. And of course even if I get a handful of duplicates, it doesn't really hurt my data in any way, just produces a very small amount of less variation compared to if I avoided it completely.

All that said, we now have a `respondent_id` variable that is unique to each respondent, so perhaps we could leverage that to just get a unique ID directly instead of by sampling. Only issue is that it gets generated inside the `sd_server()` function, so you can't obtain the `respondent_id` beforehand, so not sure if it can be directly used. 

One thought that might work though is to keep trying to randomly sample a `respID` until you get one that isn't yet in the data. In your server chunk something like this:

```r
# Get all previously used respIDs
data <- sd_get_data(db)
respIDs <- unique(data$respID)

# Sample a respID from full design file
design <- readr::read_csv("choice_questions.csv")
respID <- 1
# Keep sampling until you get one that hasn't yet been used
while (respID %in% respIDs) {
  respID <- sample(design$respID, 1)  
}

# Store the respondentID
sd_store_value(respID)
```

This should work to avoid duplicates, though there is a chance that if you have multiple concurrent respondents that they may still have a duplicate (e.g. the sampled `respID` is `2` for both current respondents, and `2` wasn't yet used by others). Chances are lower with this approach though.

This doesn't address the ability to reuse `respID` values that were not completes, but that's harder to do, and honestly I don't think any conjoint software out there does this (might be wrong). I just move on to another random `respID`.

**Comment by jhelvy** [comment]
Well, you'd probably want to make some modifications as this will run into an infinite loop once all respIDs have been used up. Like if you knew ahead of time you had `N` unique respIDs, you could check if `length(unique(data$respID)) == N`. If `TRUE`, then that means you've used them all up, so you could add some code to just close the session immediately so you don't go into an infinite loop. 

I'm going to close this for now since there's a working solution now. We also modified the setup on the repo so that questions like this can be posted on the discussion board, reserving issues for actual problems with the package. So feel free to post there in the future for help with certain things you're trying to do.

**Comment by jhelvy** [comment]
FYI, discussion board is [here](https://github.com/orgs/surveydown-dev/discussions)
